Controllers/UploadFileController.cs
using LawyerWbSite.DAL;
using LawyerWbSite.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LawyerWbSite.Controllers
{
    public class UploadFileController : Controller
    {
        LawyerOfficeContext_test db = new LawyerOfficeContext_test();
        //       [HttpPost]
        [Authorize]
        public ActionResult Index()//[Bind(Include = "DocumentID,DocumentName,DocumentPath,LawyerUsername,CaseName")] Document document)
        {

            var getLawyer = db.Lawyers.ToList();
            SelectList LawyerList = new SelectList(getLawyer, "LawyerID", "Username");
            ViewBag.DropDownLawyerList = LawyerList;//new SelectList(new[] { "-" });

            var getCase = db.Cases.ToList();
            SelectList CaseList = new SelectList(getCase, "CaseID", "CaseName");
            ViewBag.DropDownCaseList = CaseList;//new SelectList(new[] { "-" });
            //foreach (string upload in Request.Files)
            //{
            //    if (Request.Files[upload].FileName != "")
            //    {
            //        string path = AppDomain.CurrentDomain.BaseDirectory + "/App_Data/uploads/";
            //        string filename = Path.GetFileName(Request.Files[upload].FileName);
            //        Request.Files[upload].SaveAs(Path.Combine(path, filename));

            //        //upload into sql
            //        Document document = new Document();

            //        document.DocumentPath = path;
            //        document.DocumentName = filename;


            //        db.Documents.Add(document);

            //        db.SaveChanges();
            //    }
            //}
            return View();// ("Upload");
        }


        public ActionResult Downloads()
        {
            var dir = new System.IO.DirectoryInfo(Server.MapPath("~/App_Data/files/"));
            System.IO.FileInfo[] fileNames = dir.GetFiles("*.*"); List<string> items = new List<string>();
            foreach (var file in fileNames)
            {
                items.Add(file.Name);
            }
            return View(items);
        }

        public FileResult Download(string ImageName)
        {
            var FileVirtualPath = "~/App_Data/files/" + ImageName;
            return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));
        }


        //// GET: UploadFile
        //public ActionResult Index(HttpPostedFileBase file)
        //{

        //    ViewBag.Message = "index";
        //    try
        //    {
        //        if (file.ContentLength > 0)
        //        {
        //            var fileName = Path.GetFileName(file.FileName);
        //            var path = Path.Combine(Server.MapPath("~/App_Data/files"), fileName);
        //            file.SaveAs(path);
        //        }
        //        ViewBag.message = "Upload successful";
        //        return View();
        //        //return RedirectToAction("Index", "UploadFile");
        //    }
        //    catch
        //    {

        //        ViewBag.Message = "Upload failed";
        //        return View();
        //        //return RedirectToAction("Index", "UploadFile");
        //    }


        //    //return View();
        //}



        [HttpPost]
        public ActionResult Index(Document document,HttpPostedFileBase file)//,[Bind(Include = "LawyerUsername,CaseName")] Document document)
        {
           
            //ViewBag.Message = "Upload";
            try
            {
                if (file.ContentLength > 0)
                {
                    string fileName = Path.GetFileName(file.FileName);
                    string path = Path.Combine(Server.MapPath("~/App_Data/files"), fileName);
                         
                    document.DocumentName = file.FileName;
                    //get the lawyer username from dropdown list
                    string selectLawyerID = Request.Form["LawyerUsername_DropDown"].ToString();
                    var LawyerList = db.Lawyers.ToList();
                    for (int i=0;i< LawyerList.Count;i++)
                    {
                        if (LawyerList[i].LawyerID.ToString().Equals(selectLawyerID))
                        {
                            document.LawyerUsername = LawyerList[i].Username;
                            break;
                        }
                    }
                    //get the case name from dropdown list
                    string selectCaseID = Request.Form["Case_DropDow"].ToString();
                    var CaseList = db.Cases.ToList();
                    for (int i = 0; i < CaseList.Count; i++)
                    {
                        if (CaseList[i].CaseID.ToString().Equals(selectCaseID))
                        {
                            document.CaseName = CaseList[i].CaseName;
                            break;
                        }
                    }


                    db.Documents.Add(document);
                    db.SaveChanges();

                    file.SaveAs(path);

                }
               // ss = "Upload successful";
                ViewBag.message = "Upload successful";
                return RedirectToAction("Index", "Document");
            }
            catch
            {
               // ss = "Upload successful";
                ViewBag.Message = "Upload failed";
                return RedirectToAction("Index", "Document");
            }

            //return View("Upload");
        }



    }
}

Views/UploadFile/Downloads.cshtml
@{
    Layout = null;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Downloads</title>
</head>
<body>
    <div> 
        <h2>Documents</h2>
        <table >
            <tr>
                <th>File Name</th>
                <th>&nbsp &nbsp</th>
                <th>Link</th>
            </tr>
            @for (var i = 0; i <= Model.Count - 1; i++)
            {
                <tr>
                    <td>@Model[i].ToString() </td>
                    <td>&nbsp &nbsp</td>
                    <td>@Html.ActionLink("Download", "Download", new { ImageName = @Model[i].ToString() }) </td>
                </tr>
            }
        </table>
    </div>
</body>
</html>

Views/UploadFile/Index.cshtml
@model LawyerWbSite.Models.Document
@{
    Layout = null;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script type="text/javascript">
	
    </script>
</head>
<body>

  
    <div> 
    

    
       
    @using (Html.BeginForm("Index", "UploadFile", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        
        <fieldset>
            <legend>Upload a file</legend>
            @Html.AntiForgeryToken()

            <div class="editor-field">
                <div class="form-group">
                    @Html.Label("CaseName")
                    @Html.DropDownList("Case_DropDow", (SelectList)ViewBag.DropDownCaseList)
                 </div>
                <br />
                <div class="form-group">
                    @Html.Label("LawyerUsername")
                    @Html.DropDownList("LawyerUsername_DropDown", (SelectList)ViewBag.DropDownLawyerList)
                </div>
                    @Html.TextBox("file", "", new { type = "file" })
                <br />
                </div>

            <div class="editor-field">
                <input type="submit" value="Upload" name="submitme" id="submitme"/>
            </div>
        </fieldset>

       }
       
         
        
   </div>

     
</body>
</html>

Views/UploadFile/Uploadyyy.cshtml
@model LawyerWbSite.Models.Document

@{
    ViewBag.Title = "Upload";
}

<h2>Upload</h2>
<script src="~/Scripts/jquery-1.11.1.min.js"></script>
<script>
    $(document).ready(function () {
        $('#btnUploadFile').on('click', function () {
            var data = new FormData();
            var files = $("#fileUpload").get(0).files;
            // Add the uploaded image content to the form data collection
            if (files.length > 0) {
                data.append("UploadedImage", files[0]);
            }
            // Make Ajax request with the contentType = false, and procesDate = false
            var ajaxRequest = $.ajax({
                type: "POST",
                url: "UploadFile/Index",
                contentType: false,
                processData: false,
                data: data
            });

            ajaxRequest.done(function (xhr, textStatus) {
                // Do other operation
            });
        });
    });
</script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Document</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DocumentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DocumentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DocumentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DocumentPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DocumentPath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DocumentPath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LawyerUsername, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LawyerUsername, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LawyerUsername, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CaseName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CaseName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CaseName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<input type="file" name="FileUpload1" id="fileUpload" /><br />
<input id="btnUploadFile" type="button" value="Upload File" />
@*@Html.ActionLink("Documents", "Downloads")*@

Views/UploadFile/ooooo.cshtml
@model LawyerWbSite.Models.Document

@{
    ViewBag.Title = "Upload";
}

<h2>Upload</h2>
<script src="~/Scripts/jquery-1.11.1.min.js"></script>
<script>
    $(document).ready(function () {
        $('#btnUploadFile').on('click', function () {
            var data = new FormData();
            var files = $("#fileUpload").get(0).files;
            // Add the uploaded image content to the form data collection
            if (files.length > 0) {
                data.append("UploadedImage", files[0]);
            }
            // Make Ajax request with the contentType = false, and procesDate = false
            var ajaxRequest = $.ajax({
                type: "POST",
                url: "UploadFile/Index",
                contentType: false,
                processData: false,
                data: data
            });

            ajaxRequest.done(function (xhr, textStatus) {
                // Do other operation
            });
        });
    });
</script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Document</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DocumentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DocumentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DocumentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DocumentPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DocumentPath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DocumentPath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LawyerUsername, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LawyerUsername, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LawyerUsername, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CaseName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CaseName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CaseName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<input type="file" name="FileUpload1" id="fileUpload" /><br />
<input id="btnUploadFile" type="button" value="Upload File" />
@*@Html.ActionLink("Documents", "Downloads")*@